[package]
name = "py5"
version = "1.2.6"
edition = "2021"
description = "A minimalist Python interpreter written in Rust."
license = "MIT"

[package.metadata]
exclude = [".DS_Store"]

[dependencies]

[profile.dev]
opt-level = 0
debug = false
split-debuginfo = "unpacked"

[profile.release]
opt-level = "s"
lto = true